; AddVariables.asm - Chapter 3 example.

COMMENT !
Modify the AddVariables program so it uses 64-bit variables. 
Describe the syntax errors generated by the assembler and 
what steps you took to resolve the errors.

My comments: This program is going to throw so many errors
!

ExitProcess PROTO

.data
firstval  qword 20002000h
secondval qword 11111111h
thirdval  qword 22222222h
sum qword 0

.code
main proc
	
	mov rcx, firstval	; move first value to rcx a 64bit register
	add rcx, secondval  ; add second value to rcx
	add rcx, thirdval   ; add thrid value to rcx
	mov sum, rcx		; mov sum to rcx register

	invoke ExitProcess
main endp
end main
